### thymeleaf
GET http://localhost:8707/easy

### Test Controller
GET http://localhost:8707/easy/get

### Test Controller
GET http://localhost:8708/easy/get

### Trigger Test Controller
GET http://localhost:8708/easy/trigger

###
GET http://localhost:8707/easy/rest/John

###
GET http://localhost:8707/easy/rest/example/44

#Camel

#Status
###
GET http://localhost:8707/easy/camel/status

###
GET http://localhost:8707/easy/camel/v3/users?testParam=TestData

#Test Rest Service
###
POST http://localhost:8707/easy/camel/api/bean
Content-Type: application/json

{
  "id": 1,
  "name": "World"
}


###
POST http://localhost:8707/easy/api/books
Content-Type: application/json

{
  "id": 1,
  "title": "World",
  "author": "World"
}

###
GET http://localhost:8707/easy/api/books