services:
  solr1:
    image: solr:8.11.1
    container_name: solr1
    ports:
      - "8983:8983"
    volumes:
      - ./solr-cloud/security.json:/var/security.json
      - .:/mnt/config
      - solr:/var/solr
    environment:
      - ZK_HOST=zoo1:2182
    depends_on:
      - zoo1
    tty: true
    stdin_open: true
  zoo1:
    tty: true
    image: zookeeper:3.6.2
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2182
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2182
  kcproxy:
    ports:
      - '18081:8080'
    environment:
      - KEYCLOAK_HOST=zoom_keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_PROXY_PORT=8080
      - MESSAGE_QUEUE_HOST=rabbitmq
      - MESSAGE_QUEUE_USERNAME=callrec
      - MESSAGE_QUEUE_PASSWORD=callrec
    container_name: zoom_kc_proxy
    hostname: kcproxy
    depends_on:
      - rabbitmq
      - keycloak
      - postgres
    image: 'artifactory.zoomint.com/zoomint/keycloak-api-proxy:3.3.0'
  keycloak:
    ports:
      - '18080:8080'
    environment:
      - JDBC_PARAMS=currentSchema=keycloak
      - DB_DATABASE=eleveo_default_db
      - DB_SCHEMA=keycloak
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - DB_VENDOR=postgres
      - DB_ADDR=zoom_postgres
      - ENABLE_INTERNATIONALIZATION=true
      - JAVA_OPTS=-server
      - KEYCLOAK_DEFAULT_THEME=eleveo
      - KEYCLOAK_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_VERSION=20.28.2
      - KEYCLOAK_WELCOME_THEME=eleveo
      - MASTER_CLIENT_DEFAULT_ROLES=manage-clients,manage-users,view-realm
      - MASTER_CLIENT_NAME=client-management-app
      - MASTER_CLIENT_SECRET=password
      - MESSAGE_QUEUE_HOST=rabbitmq
      - MESSAGE_QUEUE_PASSWORD=callrec
      - MESSAGE_QUEUE_PORT=5672
      - MESSAGE_QUEUE_USERNAME=callrec
      - ROOT_LOGLEVEL=INFO
      - SMTP_FROM=keycloak.server@zoomint.com
      - SMTP_HOST=172.17.0.4
      - SMTP_PASSWORD=password
      - SMTP_PORT=1025
      - SMTP_USERNAME=any
      - X509_CA_BUNDLE=/zoom-ca-bundle.crt
      - ZQM_VERSION=ic_do_rici
      - 'true'
    container_name: zoom_keycloak
    hostname: zoom_keycloak
    depends_on:
      - rabbitmq
      - postgres
    image: 'artifactory.zoomint.com/zoomint/keycloak:20.28.2'
  rabbitmq:
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_PASS=callrec
      - RABBITMQ_DEFAULT_USER=callrec
    container_name: rabbitmq
    hostname: rabbitmq
    image: 'rabbitmq:3-management'
  postgres:
    container_name: 'zoom_postgres'
    hostname: 'zoom_postgres'
    image: 'postgres:15.6'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=eleveo_default_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata_correct:/var/lib/postgresql/data
#  encourage-data:
#    container_name: 'encourage_data'
#    image: 'eleveo/encourage/encourage-data:20.6.9-snapshot.unknown.build'
#    ports:
#      - '8300:8300'
#    environment:
#      - DB_ADDRESS=jdbc:postgresql://zoom_postgres:5432/
#      - KEYCLOAK_SERVER_URL=http://kcproxy:18081/auth
#    depends_on:
#      - keycloak
#      - postgres
  automated-qm:
    container_name: 'automated_qm'
    image: 'eleveo/automated-qm:1.0.7'
    ports:
      - '8207:8207'
    environment:
      - DB_ADDRESS=jdbc:postgresql://zoom_postgres:5432/
      - DATABASE_NAME=eleveo_default_db
      - application.keycloak.server-url=http://zoom_keycloak:8080/auth
      - application.keycloak.master-password=password
      - DATABASE_HOST=zoom_postgres
      - application.datasource.username=postgres
      - application.datasource.password=postgres
      - review.period=5000
      - review.maxNumber=600
      - review.maxCores=3
    depends_on:
      - keycloak
      - postgres
volumes:
  pgdata_correct:
  solr:

#  /usr/bin/pg_dump --dbname=postgresql://postgres:postgres@10.17.50.85:5432/eleveo_default_db --file=/home/dmytro/eleveo_default_db_dump.sql --host=10.17.50.85

#  scp -r root@vm085.eng.cz.zoomint.com:/opt/callrec/data/calls /opt/callrec/data/
#  scp -r root@vm085.eng.cz.zoomint.com:/opt/callrec/data/scorecard /opt/callrec/data/

  #kubectl get secret/keycloak-master-client -ndefault -ojsonpath='{.data.secret}{"\n"}' | base64 -d;echo
#kubectl get secret/postgres-secrets -ndefault -ojsonpath='{.data.db\.pass}{"\n"}' | base64 -d;echo


# cd  ~/dev/projects/interaction-service && ./gradlew bootRun --args='--spring.profiles.active=run-with-compose'
# cd  ~/dev/projects/data/service && mvn spring-boot:run -Dspring-boot.run.profiles=run-with-compose
# cd  ~/dev/projects/conversations/service && mvn spring-boot:run -Dspring-boot.run.profiles=run-with-compose
# cd  ~/dev/projects/correlation/service && mvn spring-boot:run -Dspring-boot.run.profiles=run-with-compose
# cd  ~/dev/projects/zqm-connector/service && mvn spring-boot:run -Dspring-boot.run.profiles=run-with-compose
# cd  ~/dev/projects/scheduler/service && mvn spring-boot:run -Dspring-boot.run.profiles=run-with-compose
# cd  ~/dev/projects/framework/service && mvn spring-boot:run -Dspring-boot.run.profiles=run-with-compose
# cd  ~/dev/projects/speechrec && ./gradlew bootRun --args='--spring.profiles.active=run-with-compose'
# cd  ~/dev/projects/automatedqm && ./gradlew bootRun --args='--spring.profiles.active=run-with-compose'



#  curl -X DELETE http://localhost:8108/api/correlation-range/
#  curl -X DELETE http://localhost:8107/api/v3/conversations/
#  curl -X DELETE http://localhost:8300/api/v3/events/
#  curl -X DELETE http://localhost:8300/api/v3/tasks/

  #  curl -X DELETE http://localhost:8108/api/correlation-range/ && curl -X DELETE http://localhost:8107/api/v3/conversations/ && curl -X DELETE http://localhost:8300/api/v3/events/ && curl -X DELETE http://localhost:8300/api/v3/tasks/
