services:
  kcproxy:
    ports:
      - '18081:8080'
    environment:
      - KEYCLOAK_HOST=zoom_keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_PROXY_PORT=8080
      - MESSAGE_QUEUE_HOST=rabbitmq
    container_name: zoom_kc_proxy
    hostname: kcproxy
    depends_on:
      - rabbitmq
      - keycloak
      - postgres
    image: 'artifactory.zoomint.com/zoomint/keycloak-api-proxy:3.3.0'
  keycloak:
    ports:
      - '18080:8080'
    environment:
      - JDBC_PARAMS=currentSchema=keycloak
      - DB_DATABASE=eleveo_default_db
      - DB_SCHEMA=keycloak
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - DB_VENDOR=postgres
      - DB_ADDR=zoom_postgres
      - ENABLE_INTERNATIONALIZATION=true
      - JAVA_OPTS=-server
      - KEYCLOAK_DEFAULT_THEME=eleveo
      - KEYCLOAK_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_VERSION=20.28.2
      - KEYCLOAK_WELCOME_THEME=eleveo
      - MASTER_CLIENT_DEFAULT_ROLES=manage-clients,manage-users,view-realm
      - MASTER_CLIENT_NAME=client-management-app
      - MASTER_CLIENT_SECRET=password
      - MESSAGE_QUEUE_HOST=rabbitmq
      - MESSAGE_QUEUE_PASSWORD=guest
      - MESSAGE_QUEUE_PORT=5672
      - MESSAGE_QUEUE_USERNAME=guest
      - ROOT_LOGLEVEL=INFO
      - SMTP_FROM=keycloak.server@zoomint.com
      - SMTP_HOST=172.17.0.4
      - SMTP_PASSWORD=password
      - SMTP_PORT=1025
      - SMTP_USERNAME=any
      - X509_CA_BUNDLE=/zoom-ca-bundle.crt
      - ZQM_VERSION=ic_do_rici
      - 'true'
    container_name: zoom_keycloak
    hostname: zoom_keycloak
    depends_on:
      - rabbitmq
      - postgres
    image: 'artifactory.zoomint.com/zoomint/keycloak:20.28.2'
  rabbitmq:
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_USER=guest
    container_name: rabbitmq
    hostname: rabbitmq
    image: 'rabbitmq:3-management'
  postgres:
    container_name: 'zoom_postgres'
    hostname: 'zoom_postgres'
    image: 'postgres:12.14'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata_correct:/var/lib/postgresql/data
  encourage-data:
    container_name: 'encourage_data'
    image: 'eleveo/encourage/encourage-data:20.6.9-snapshot.unknown.build'
    ports:
      - '8300:8300'
    environment:
      - DB_ADDRESS=jdbc:postgresql://zoom_postgres:5432/
      - KEYCLOAK_SERVER_URL=http://kcproxy:18081/auth
    depends_on:
      - keycloak
      - postgres
volumes:
  pgdata_correct:


