services:
  solr1:
    image: solr:8.11.1
    container_name: solr1
    ports:
      - "8983:8983"
    volumes:
      - ./solr-cloud/security.json:/var/security.json
      - .:/mnt/config
      - solr:/var/solr
    environment:
      - ZK_HOST=zoo1:2182
    depends_on:
      - zoo1
    tty: true
    stdin_open: true
  zoo1:
    tty: true
    image: zookeeper:3.6.2
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2182
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2182
  kcproxy:
    ports:
      - '18081:8080'
    environment:
      - KEYCLOAK_HOST=zoom_keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_PROXY_PORT=8080
      - MESSAGE_QUEUE_HOST=rabbitmq
      - MESSAGE_QUEUE_USERNAME=callrec
      - MESSAGE_QUEUE_PASSWORD=callrec
    container_name: zoom_kc_proxy
    hostname: kcproxy
    depends_on:
      - rabbitmq
      - keycloak
      - postgres
    image: 'artifactory.zoomint.com/zoomint/keycloak-api-proxy:3.3.0'
  keycloak:
    ports:
      - '18080:8080'
    environment:
      - JDBC_PARAMS=currentSchema=keycloak
      - DB_DATABASE=eleveo_default_db
      - DB_SCHEMA=keycloak
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - DB_VENDOR=postgres
      - DB_ADDR=zoom_postgres
      - ENABLE_INTERNATIONALIZATION=true
      - JAVA_OPTS=-server
      - KEYCLOAK_DEFAULT_THEME=eleveo
      - KEYCLOAK_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_VERSION=20.35.1
      - KEYCLOAK_WELCOME_THEME=eleveo
      - MASTER_CLIENT_DEFAULT_ROLES=manage-clients,manage-users,view-realm
      - MASTER_CLIENT_NAME=client-management-app
      - MASTER_CLIENT_SECRET=password
      - MESSAGE_QUEUE_HOST=rabbitmq
      - MESSAGE_QUEUE_PASSWORD=callrec
      - MESSAGE_QUEUE_PORT=5672
      - MESSAGE_QUEUE_USERNAME=callrec
      - ROOT_LOGLEVEL=INFO
      - MESSAGE_QUEUE_VHOST=/
      - SMTP_FROM=keycloak.server@zoomint.com
      - SMTP_HOST=172.17.0.4
      - SMTP_PASSWORD=password
      - SMTP_PORT=1025
      - SMTP_USERNAME=any
      - X509_CA_BUNDLE=/zoom-ca-bundle.crt
      - ZQM_VERSION=ic_do_rici
    container_name: zoom_keycloak
    hostname: zoom_keycloak
    depends_on:
      - rabbitmq
      - postgres
    image: 'artifactory.zoomint.com/zoomint/keycloak:20.35.1'
  rabbitmq:
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_PASS=callrec
      - RABBITMQ_DEFAULT_USER=callrec
    container_name: rabbitmq
    hostname: rabbitmq
    image: 'rabbitmq:3-management'
  postgres:
    container_name: 'zoom_postgres'
    hostname: 'zoom_postgres'
    image: 'postgres:15.6'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=eleveo_default_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata_correct:/var/lib/postgresql/data





#
#  encourage-data:
#    container_name: 'encourage_data'
#    image: 'eleveo/encourage/encourage-data:20.7.10'
#    deploy:
#      resources:
#        limits:
#          memory: 1G
#    volumes:
#      - /tmp/:/home
#    ports:
#      - '8300:8300'
#    environment:
#      - data.database.address=jdbc:postgresql://zoom_postgres:5432/
#      - data.database.username=postgres
#      - data.database.password=postgres
#      - data.database.dbName=eleveo_default_db
#      - SPRING.RABBITMQ.HOST=rabbitmq
#      - SPRING.RABBITMQ.USERNAME=callrec
#      - SPRING.RABBITMQ.PASSWORD=callrec
#      - keycloak-client-token-provider.serverUrl=http://zoom_keycloak:8080/auth
##      - keycloak-client-token-provider.serverUrl=http://localhost:18080/auth
#      - keycloak-client-token-provider.realm=default
#      - keycloak-client-token-provider.master-client-secret=password
##      - JAVA_TOOL_OPTIONS="['-XX:HeapDumpPath=/home', '-XX:+HeapDumpOnOutOfMemoryError']"
##      - JAVA_TOOL_OPTIONS='-XX:+HeapDumpOnOutOfMemoryError'
#      - JAVA_TOOL_OPTIONS=-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home
##      - JAVA_TOOL_OPTIONS='-XX:HeapDumpPath=/home/dmytro/dev/heapdump/'
##      - JAVA_TOOL_OPTIONS='-XX:+HeapDumpOnOutOfMemoryError,-XX:HeapDumpPath=/home/dmytro/dev/heapdump/,--enable-monitoring=heapdump'
#    depends_on:
#      - keycloak
#      - postgres
#      - kcproxy
#
#  encourage-zqm-connector:
#    container_name: 'encourage_zqm_connector'
#    image: 'eleveo/encourage/encourage-zqm-connector:20.7.10'
#    deploy:
#      resources:
#        limits:
#          memory: 1G
#    volumes:
#      - /tmp/:/home
#    ports:
#      - '8201:8201'
#    environment:
#      - ENC-ZQM-CONNECTOR_WBSC-DATABASE_ADDRESS=jdbc:postgresql://zoom_postgres:5432/
#      - ENC-ZQM-CONNECTOR_WBSC-DATABASE_USERNAME=postgres
#      - ENC-ZQM-CONNECTOR_WBSC-DATABASE_PASSWORD=postgres
#      - ENC-ZQM-CONNECTOR_WBSC-DATABASE_HOST=zoom_postgres
#      - ENC-ZQM-CONNECTOR_WBSC-DATABASE_PORT=5432
#      - ENC-ZQM-CONNECTOR_WBSC-DATABASE_dbName=eleveo_default_db
#      - ENC-ZQM-CONNECTOR.BATCH-SIZE=20
#      - ENC-ZQM-CONNECTOR.SPEECH-REC-ENABLED=true
#      - SPRING.RABBITMQ.HOST=rabbitmq
#      - SPRING.RABBITMQ.USERNAME=callrec
#      - SPRING.RABBITMQ.PASSWORD=callrec
#      - enc-zqm-connector.dataApi=http://encourage_data:8300/api
#      - enc-zqm-connector.qmApiUrl=http://localhost:8080/qm/api
#        enc-zqm-connector.callrecApi.url=http://mc_interaction_service:8081
#
#      - keycloak-client-token-provider.serverUrl=http://zoom_keycloak:8080/auth
#      - keycloak-client-token-provider.realm=default
#      - keycloak-client-token-provider.master-client-secret=password
#      - JAVA_TOOL_OPTIONS=-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home
#    depends_on:
#      - keycloak
#      - postgres
#      - kcproxy
#
#  encourage-correlation:
#    container_name: 'encourage_correlation'
#    image: 'eleveo/encourage/encourage-correlation:20.7.5'
#    deploy:
#      resources:
#        limits:
#          memory: 1G
#    volumes:
#      - /tmp/:/home
#    ports:
#      - '8108:8108'
#    environment:
#      - enc-correlation.database.address=jdbc:postgresql://zoom_postgres:5432/
#      - enc-correlation.database.username=postgres
#      - enc-correlation.database.password=postgres
#      - enc-correlation.database.dbName=eleveo_default_db
#      - SPRING.RABBITMQ.HOST=rabbitmq
#      - SPRING.RABBITMQ.USERNAME=callrec
#      - SPRING.RABBITMQ.PASSWORD=callrec
#      - keycloak-client-token-provider.serverUrl=http://zoom_keycloak:8080/auth
#      - keycloak-client-token-provider.realm=default
#      - keycloak-client-token-provider.master-client-secret=password
#      - JAVA_TOOL_OPTIONS=-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home
#    depends_on:
#      - keycloak
#      - postgres
#      - kcproxy
#
#  encourage-conversations:
#    container_name: 'encourage_conversations'
#    image: 'eleveo/encourage/encourage-conversations:20.7.9'
#    deploy:
#      resources:
#        limits:
#          memory: 1G
#    volumes:
#      - /tmp/:/home
#    ports:
#      - '8107:8107'
#    environment:
#      - enc-conversations.solr.collection=conversations
#      - enc-conversations.solr.host=solr1
#      - enc-conversations.solr.port=8983
#      - SPRING.RABBITMQ.HOST=rabbitmq
#      - SPRING.RABBITMQ.PORT=5672
#      - SPRING.RABBITMQ.USERNAME=callrec
#      - SPRING.RABBITMQ.PASSWORD=callrec
#      - SPRING.RABBITMQ.virtual-host=/
#      - spring.rabbitmq.addresses=rabbitmq:5672
#      - camel.rest.component.rabbitmq.hostname=rabbitmq
#      - camel.rest.component.rabbitmq.port-number=5672
#      - camel.rest.component.rabbitmq.username=callrec
#      - camel.rest.component.rabbitmq.password=callrec
#      - camel.rest.component.rabbitmq.vhost=/
#      - enc-conversations.solr.zookeeper=zoo1:2182
#      - enc-conversations.solr-configset-path=/app/config/solr-config-set/conversation
#      - hide.gender=false
#      - processing.delay=0
#      - keycloak-client-token-provider.serverUrl=http://zoom_keycloak:8080/auth
#      - keycloak-client-token-provider.realm=default
#      - keycloak-client-token-provider.master-client-secret=password
#      - JAVA_TOOL_OPTIONS=-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home
#    depends_on:
#      - keycloak
#      - postgres
#      - kcproxy
#
#  mc-interaction-service:
#    container_name: 'mc_interaction_service'
#    image: 'eleveo/mc/eleveo-mc-interaction-service:1.29.3'
#    deploy:
#      resources:
#        limits:
#          memory: 1G
#    volumes:
#      - /opt/callrec/:/opt/callrec
#    ports:
#      - '8081:8081'
#    environment:
#      - spring.datasource.url=jdbc:postgresql://zoom_postgres:5432/eleveo_default_db
#      - spring.datasource.username=postgres
#      - spring.datasource.password=postgres
#      - spring.datasource.hikari.schema=callrec
#      - spring.datasource.hikari.username=postgres
#      - spring.datasource.hikari.password=postgres
#      - spring.rabbitmq.username=callrec
#      - spring.rabbitmq.password=callrec
#      - keycloak-client-management.keycloak-server-url=http://zoom_keycloak:8080/auth
#      - keycloak-client-management.application-name=SEGS
#      - keycloak-client-token-provider.serverUrl=http://zoom_keycloak:8080/auth
#      - keycloak-client-token-provider.realm=default
#      - keycloak-client-token-provider.master-client-secret=password
#      - interaction-service.temp-max-age=60m
#      - interaction-service.media-location=/opt/callrec/data/calls
#      - interaction-service.keycloak.url=http://zoom_keycloak:8080/auth
#      - interaction-service.keycloak.frontend-url=http://zoom_keycloak:8080/auth
#      - interaction-service.keycloak.realm=default
#      - interaction-service.rabbitmq-management.username=callrec
#      - interaction-service.rabbitmq-management.password=callrec
#      - interaction-service.rabbitmq-management.url=http://rabbitmq:15672/api
#      - spring.rabbitmq.host=rabbitmq
#      - spring.rabbitmq.port=5672
#      - spring.rabbitmq.username=callrec
#      - spring.rabbitmq.password=callrec
#      - JAVA_TOOL_OPTIONS=-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home
#    depends_on:
#      - keycloak
#      - postgres
#      - kcproxy
#
#  speechrec-core:
#    container_name: 'speechrec_core'
#    image: 'eleveo/speechrec/core:3.27.0'
#    deploy:
#      resources:
#        limits:
#          memory: 1G
#    ports:
#      - '8080:8080'
#    environment:
#      - application.web-client.segment-service-url=http://mc_interaction_service:8081
#      - application.keycloak.server-url=http://zoom_keycloak:8080/auth
#      - application.keycloak.realm=default
#      - application.keycloak.master-password=password
#      - spring.rabbitmq.username=callrec
#      - spring.rabbitmq.password=callrec
#      - spring.rabbitmq.host=rabbitmq
#      - spring.r2dbc.schema=speechrec_core
#      - spring.r2dbc.database=eleveo_default_db
#      - spring.r2dbc.host=zoom_postgres
#      - spring.r2dbc.port=5432
#      - spring.r2dbc.username=postgres
#      - spring.r2dbc.password=postgres
#      - JAVA_TOOL_OPTIONS=-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home
#    depends_on:
#      - keycloak
#      - postgres
#      - kcproxy
#
#  automated-qm:
#    container_name: 'automated_qm'
#    image: 'eleveo/automated-qm:1.0.15'
#    ports:
#      - '8207:8207'
#    environment:
#      - DB_ADDRESS=jdbc:postgresql://zoom_postgres:5432/
#      - DATABASE_NAME=eleveo_default_db
#      - application.keycloak.server-url=http://zoom_keycloak:8080/auth
#      - application.keycloak.master-password=password
#      - DATABASE_HOST=zoom_postgres
#      - application.datasource.username=postgres
#      - application.datasource.password=postgres
#      - review.period=5000
#      - review.maxNumber=600
#      - review.maxCores=3
#    depends_on:
#      - keycloak
#      - postgres
#      - kcproxy





volumes:
  pgdata_correct:
  solr:


# psql should be installed and .pgpass should be created with content:
#  localhost:5432:eleveo_default_db:postgres:postgres and permissions 600
# 0. cd /home/dmytro/dev/projects/easyboot/docker-compose/work
# 1.  /usr/bin/pg_dump --dbname=postgresql://postgres:postgres@10.17.50.85:5432/eleveo_default_db --file=/home/dmytro/eleveo_default_db_dump_085.sql --host=10.17.50.85
# 2. docker-compose down   and  docker volume prune -f
# 3. docker-compose run -d --name zoom_postgres -p 5432:5432 postgres
#  or better - docker-compose up
# 4. /usr/bin/psql --host=localhost --port=5432 dbname=eleveo_default_db --username=postgres --file="/home/dmytro/eleveo_default_db_dump_085.sql"
# 5. docker-compose down
# 6. docker-compose up



#  scp -r root@vm085.eng.cz.zoomint.com:/opt/callrec/data/calls /opt/callrec/data/
#  scp -r root@vm085.eng.cz.zoomint.com:/opt/callrec/data/scorecard /opt/callrec/data/

  #kubectl get secret/keycloak-master-client -ndefault -ojsonpath='{.data.secret}{"\n"}' | base64 -d;echo
#kubectl get secret/postgres-secrets -ndefault -ojsonpath='{.data.db\.pass}{"\n"}' | base64 -d;echo


# cd  ~/dev/projects/interaction-service && ./gradlew bootRun --args='--spring.profiles.active=run-with-compose'
# cd  ~/dev/projects/data/service && mvn spring-boot:run -Dspring-boot.run.profiles=run-with-compose
# cd  ~/dev/projects/conversations/service && mvn spring-boot:run -Dspring-boot.run.profiles=run-with-compose
# cd  ~/dev/projects/correlation/service && mvn spring-boot:run -Dspring-boot.run.profiles=run-with-compose
# cd  ~/dev/projects/zqm-connector/service && mvn spring-boot:run -Dspring-boot.run.profiles=run-with-compose
# cd  ~/dev/projects/scheduler/service && mvn spring-boot:run -Dspring-boot.run.profiles=run-with-compose
# cd  ~/dev/projects/framework/service && mvn spring-boot:run -Dspring-boot.run.profiles=run-with-compose
# cd  ~/dev/projects/speechrec && ./gradlew bootRun --args='--spring.profiles.active=run-with-compose'
# cd  ~/dev/projects/automatedqm && ./gradlew bootRun --args='--spring.profiles.active=run-with-compose'



#  curl -X DELETE http://localhost:8108/api/correlation-range/
#  curl -X DELETE http://localhost:8107/api/v3/conversations/
#  curl -X DELETE http://localhost:8300/api/v3/events/
#  curl -X DELETE http://localhost:8300/api/v3/tasks/

  #  curl -X DELETE http://localhost:8108/api/correlation-range/ && curl -X DELETE http://localhost:8107/api/v3/conversations/ && curl -X DELETE http://localhost:8300/api/v3/events/ && curl -X DELETE http://localhost:8300/api/v3/tasks/



#  delete from encourage.labels_to_phrases;
#  delete from encourage.speechphrases;
#  delete from encourage.labels where type = 'S';

#  curl --location --request DELETE 'http://encourage-conversations-svc:8107/api/v3/conversations/
#  curl --location --request DELETE 'http://encourage-correlation-svc:8108/api/correlation-range/'
#  curl --location --request DELETE 'http://encourage-data-svc:8300/api/v3/events'
#  curl --location --request DELETE 'http://encourage-data-svc:8300/api/v3/tasks'