apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy
  labels:
    app: easy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easy-pod
  template:
    metadata:
      labels:
        app: easy-pod
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}{{ .Values.image.nameWithTag }}"
          resources:
            requests:
              cpu: 50m
            limits:
              memory: 600Mi
          imagePullPolicy: IfNotPresent
          ports:
            - name: easy-port
              containerPort: 8707
          envFrom:
            - configMapRef:
                name: easy-configmap
          env:
            - name: APPLICATION.KEYCLOAK.MASTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-master-client
                  key: secret
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: db.host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: db.port
            - name: DATABASE_NAME
              value: auto_qm
            - name: spring.database.user
              valueFrom:
                secretKeyRef:
                  name: automated-qm-secret
                  key: spring.datasource.user
            - name: spring.database.password
              valueFrom:
                secretKeyRef:
                  name: automated-qm-secret
                  key: spring.datasource.password
            - name: params.parameter1
              valueFrom:
                configMapKeyRef:
                  key: params.parameter1
                  name: easy-configmap
            - name: params.param2
              valueFrom:
                configMapKeyRef:
                  key: params.parameter2
                  name: easy-configmap
