apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: easy-ingress
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.deployment.app.path }}
            pathType: Prefix
            backend:
              service:
                name: easy-svc
                port:
                  number: 8707
